services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - path: .env
        required: true
      - path: .env.override
        required: false
    volumes:
      - ../app:/app