name: main

on: [push]

jobs:
    phpunit:
        name: "PHPUnit tests"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: php-actions/composer@v6
              with:
                  working_dir: "app"
            - name: PHPUnit Tests
              uses: php-actions/phpunit@master
              with:
                  php_version: 8.3.10
                  version: 11.3.1
                  bootstrap: "app/vendor/autoload.php"
                  configuration: "app/phpunit.xml"